from django.contrib import admin
from progdb.progdb2.models import SlotLength, Slot, Grid, ConDay, ItemKind, SeatingKind, PersonStatus, PersonRole
from progdb.progdb2.models import RoomCapacity, Room, Revision, Tag, ItemPerson, Item, Person, Gender, CheckResult, Check
from progdb.progdb2.models import FrontLayoutKind, KitKind, KitRole, KitDepartment, KitSource, KitBasis, KitStatus
from progdb.progdb2.models import MediaStatus, KitRequest, KitThing, KitBundle, KitRoomAssignment, KitItemAssignment
from progdb.progdb2.models import Availability, KitAvailability, RoomAvailability, PersonAvailability
from progdb.progdb2.models import ConInfoInt, ConInfoString, ConInfoBool

admin.site.register(SlotLength)
admin.site.register(Slot)
admin.site.register(Grid)
admin.site.register(ConDay)
admin.site.register(ItemKind)
admin.site.register(SeatingKind)
admin.site.register(PersonStatus)
admin.site.register(PersonRole)
admin.site.register(Gender)
admin.site.register(Room)
admin.site.register(Revision)
admin.site.register(Tag)
admin.site.register(ItemPerson)
admin.site.register(Item)
admin.site.register(Person)
admin.site.register(RoomCapacity)
admin.site.register(CheckResult)
admin.site.register(Check)
admin.site.register(FrontLayoutKind)
admin.site.register(KitKind)
admin.site.register(KitRole)
admin.site.register(KitDepartment)
admin.site.register(KitSource)
admin.site.register(KitBasis)
admin.site.register(KitStatus)
admin.site.register(MediaStatus)
admin.site.register(KitRequest)
admin.site.register(KitThing)
admin.site.register(KitBundle)
admin.site.register(KitRoomAssignment)
admin.site.register(KitItemAssignment)
admin.site.register(KitAvailability)
admin.site.register(RoomAvailability)
admin.site.register(PersonAvailability)
admin.site.register(Availability)
admin.site.register(ConInfoInt)
admin.site.register(ConInfoString)
admin.site.register(ConInfoBool)
